#!/usr/bin/env node

/**
 * DISC Agent Blueprint Generator
 * 
 * Creates complete OpenClaw agent workspaces from templates and DISC profiles.
 * 
 * Usage:
 *   node create-agent.js --role=hr-specialist --name="Sarah" --output="./generated-agents"
 *   node create-agent.js --role=developer --name="Alex" --output="./generated-agents"
 */

const fs = require('fs');
const path = require('path');

// Configuration
const BASE_DIR = path.resolve(__dirname, '..');
const TEMPLATES_DIR = path.join(BASE_DIR, 'templates');
const DISC_PROFILES_DIR = path.join(BASE_DIR, 'disc-profiles');
const SKILLS_MAPPING_FILE = path.join(BASE_DIR, 'skills-mapping', 'role-skills.json');
const MODELS_MAPPING_FILE = path.join(BASE_DIR, 'models-mapping', 'role-models.json');

// Color codes for terminal output
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  red: '\x1b[31m'
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

/**
 * Load JSON file
 */
function loadJSON(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(content);
  } catch (error) {
    log(`Error loading ${filePath}: ${error.message}`, 'red');
    process.exit(1);
  }
}

/**
 * Load template file
 */
function loadTemplate(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch (error) {
    log(`Error loading template ${filePath}: ${error.message}`, 'red');
    process.exit(1);
  }
}

/**
 * Replace variables in template
 * Format: ${variable_name}
 */
function renderTemplate(template, variables) {
  return template.replace(/\$\{([^}]+)\}/g, (match, key) => {
    const value = variables[key];
    if (value === undefined) {
      log(`Warning: Missing variable "${key}" in template`, 'yellow');
      return match;
    }
    return value;
  });
}

/**
 * Generate list from array
 */
function generateList(items, format = 'bullet') {
  if (!items || items.length === 0) {
    return '  - None specified';
  }
  
  const prefix = format === 'number' ? (index) => `${index + 1}. ` : '- ';
  return items.map((item, index) => `${prefix}${item}`).join('\n');
}

/**
 * Build SOUL.md content from DISC profile and role definition
 */
function buildSoulContent(roleDef, discProfiles, variables) {
  const primaryProfile = discProfiles[roleDef.primary_disc.toLowerCase()];
  const secondaryProfile = discProfiles[roleDef.secondary_disc.toLowerCase()];
  
  const communicationStyle = primaryProfile.communication_style;
  const strengths = generateList(primaryProfile.strengths);
  
  // Build the SOUL.md content
  const soulContent = `# SOUL.md - ${variables.agent_name}

## DISC Profile: ${roleDef.primary_disc}+${roleDef.secondary_disc} (${primaryProfile.name} + ${secondaryProfile.name})

**Core Identity:** ${roleDef.personality_summary}

**Communication Style:**
- **Tone:** ${communicationStyle.tone}
- **Pacing:** ${communicationStyle.pacing}
- **Conflict Approach:** ${communicationStyle.conflict_approach}
- **Feedback Style:** ${communicationStyle.feedback_style}

**Strengths:**
${strengths}

**Boundaries:**
- ${variables.boundary_1 || 'Respect confidentiality and privacy'}
- ${variables.boundary_2 || 'Follow established guidelines and policies'}
- ${variables.boundary_3 || 'Escalate when uncertain or out of scope'}
- ${roleDef.soul_guidance?.boundaries_template || 'Maintain professional boundaries'}

**Work Rhythm:**
- **Morning:** ${variables.work_rhythm_morning || 'Review priorities and communications'}
- **Afternoon:** ${variables.work_rhythm_afternoon || 'Focus on deep work and execution'}
- **Evening:** ${variables.work_rhythm_evening || 'Document progress and plan next steps'}

---

## Who You Are

You are ${variables.agent_name}, a ${roleDef.name} agent designed to ${roleDef.description}.

**Your Role:**
${generateList(roleDef.key_traits, 'bullet')}

**Your Personality:**
${roleDef.soul_guidance?.identity_template || 'You bring the DISC-driven traits to every interaction.'}

**How You Communicate:**
${roleDef.soul_guidance?.communication_template || 'Your communication style reflects your DISC profile.'}

**Your Boundaries:**
${roleDef.soul_guidance?.boundaries_template || 'You maintain clear professional boundaries.'}

**Your Daily Rhythm:**
${roleDef.soul_guidance?.work_rhythm_template || 'You follow a structured daily rhythm.'}

---

## Key Responsibilities

${variables.responsibilities || 'See role-specific documentation for detailed responsibilities.'}

---

## Memory Guidelines

${variables.memory_guidelines || 'Document significant interactions and decisions.'}

---

## Safety & Ethics

${variables.safety_ethics || 'Follow all applicable laws, regulations, and ethical guidelines.'}

---

*Generated by DISC Agent Blueprint System - ${variables.generation_date}*
`;
  
  return soulContent;
}

/**
 * Generate skill recommendations
 */
function generateSkillRecommendations(role) {
  const skillsMapping = loadJSON(SKILLS_MAPPING_FILE);
  const roleData = skillsMapping[role];
  
  if (!roleData) {
    log(`No skill mapping found for role: ${role}`, 'yellow');
    return { recommended: [], optional: [], model: 'default', reasoning: 'No mapping available' };
  }
  
  return {
    recommended: roleData.recommended_skills,
    optional: roleData.optional_skills,
    model: roleData.model,
    reasoning: roleData.reasoning
  };
}

/**
 * Create agent workspace
 */
function createAgent(role, agentName, outputDir) {
  log(`\n${'='.repeat(60)}`, 'cyan');
  log(`DISC Agent Blueprint Generator`, 'magenta');
  log(`${'='.repeat(60)}\n`, 'cyan');
  
  // Load role definitions
  const roleDefinitions = loadJSON(path.join(DISC_PROFILES_DIR, 'role-definitions.json'));
  const discProfiles = {
    'd': loadJSON(path.join(DISC_PROFILES_DIR, 'D-dominance.json')),
    'i': loadJSON(path.join(DISC_PROFILES_DIR, 'I-influence.json')),
    's': loadJSON(path.join(DISC_PROFILES_DIR, 'S-steadiness.json')),
    'c': loadJSON(path.join(DISC_PROFILES_DIR, 'C-conscientiousness.json'))
  };
  
  // Validate role
  if (!roleDefinitions.roles[role]) {
    log(`Error: Unknown role "${role}"`, 'red');
    log(`Available roles: ${Object.keys(roleDefinitions.roles).join(', ')}`, 'yellow');
    process.exit(1);
  }
  
  const roleDef = roleDefinitions.roles[role];
  const primaryProfile = discProfiles[roleDef.primary_disc.toLowerCase()];
  const secondaryProfile = discProfiles[roleDef.secondary_disc.toLowerCase()];
  
  log(`Creating agent: ${agentName}`, 'green');
  log(`Role: ${roleDef.name}`, 'green');
  log(`DISC Profile: ${roleDef.primary_disc}+${roleDef.secondary_disc} (${primaryProfile.name} + ${secondaryProfile.name})`, 'green');
  
  // Get skill recommendations
  const skillData = generateSkillRecommendations(role);
  
  log(`\n${'─'.repeat(60)}`, 'cyan');
  log(`Skill Recommendations`, 'blue');
  log(`${'─'.repeat(60)}`, 'cyan');
  
  log(`\n${colors.cyan}Recommended Skills (review before installing):${colors.reset}`);
  skillData.recommended.forEach(skill => {
    log(`  ✓ ${skill}`);
  });
  
  log(`\n${colors.yellow}Optional Skills:${colors.reset}`);
  skillData.optional.forEach(skill => {
    log(`  ○ ${skill}`);
  });
  
  log(`\n${colors.magenta}Recommended Model:${colors.reset} ${skillData.model}`);
  log(`Reasoning: ${skillData.reasoning}`);
  
  // Create output directory
  const agentDir = path.join(outputDir, agentName.replace(/\s+/g, '-').toLowerCase());
  fs.mkdirSync(agentDir, { recursive: true });
  
  // Template variables
  const variables = {
    agent_name: agentName,
    generation_date: new Date().toISOString().split('T')[0],
    role: roleDef.name,
    primary_disc: roleDef.primary_disc,
    secondary_disc: roleDef.secondary_disc,
    primary_disc_name: primaryProfile.name,
    secondary_disc_name: secondaryProfile.name,
    personality_summary: roleDef.personality_summary,
    communication_style_tone: primaryProfile.communication_style.tone,
    communication_style_pacing: primaryProfile.communication_style.pacing,
    communication_style_conflict: primaryProfile.communication_style.conflict_approach,
    communication_style_feedback: primaryProfile.communication_style.feedback_style,
    strengths_list: generateList(primaryProfile.strengths),
    boundary_guidance: roleDef.soul_guidance?.boundaries_template || 'Maintain professional boundaries',
    work_rhythm_morning: 'Review priorities and communications',
    work_rhythm_afternoon: 'Focus on deep work and execution',
    work_rhythm_evening: 'Document progress and plan next steps',
    soul_identity_template: roleDef.soul_guidance?.identity_template || 'You bring the DISC-driven traits to every interaction.',
    soul_communication_template: roleDef.soul_guidance?.communication_template || 'Your communication style reflects your DISC profile.',
    soul_boundaries_template: roleDef.soul_guidance?.boundaries_template || 'You maintain clear professional boundaries.',
    soul_work_rhythm_template: roleDef.soul_guidance?.work_rhythm_template || 'You follow a structured daily rhythm.',
    model: skillData.model,
    reasoning: skillData.reasoning
  };
  
  // Process templates
  const templatesDir = path.join(TEMPLATES_DIR, role);
  const templateFiles = [
    'SOUL.md.template',
    'MEMORY.md.template',
    'TOOLS.md.template',
    'AGENTS.md.template',
    'HEARTBEAT.md.template',
    'config.json.template'
  ];
  
  log(`\n${'─'.repeat(60)}`, 'cyan');
  log(`Generating Workspace Files`, 'blue');
  log(`${'─'.repeat(60)}`, 'cyan');
  
  templateFiles.forEach(templateFile => {
    const templatePath = path.join(templatesDir, templateFile);
    const outputFile = templateFile.replace('.template', '');
    const outputPath = path.join(agentDir, outputFile);
    
    // Load and render template
    let content = loadTemplate(templatePath);
    content = renderTemplate(content, variables);
    
    // Write file
    fs.writeFileSync(outputPath, content);
    log(`  ✓ ${outputFile}`, 'green');
  });
  
  // Create memory directory
  const memoryDir = path.join(agentDir, 'memory');
  fs.mkdirSync(memoryDir, { recursive: true });
  log(`  ✓ memory/ (directory created)`, 'green');
  
  // Create README
  const readmeContent = `# ${agentName} - ${roleDef.name} Agent

**Generated:** ${variables.generation_date}

## Overview

${agentName} is a ${roleDef.name} agent built with the DISC Agent Blueprint System.

**DISC Profile:** ${roleDef.primary_disc}+${roleDef.secondary_disc} (${primaryProfile.name} + ${secondaryProfile.name})

**Description:** ${roleDef.personality_summary}

## Quick Start

1. **Review the generated files:**
   - \`SOUL.md\` - Personality and behavior guide
   - \`MEMORY.md\` - Long-term memory structure
   - \`TOOLS.md\` - Tools and skills configuration
   - \`AGENTS.md\` - Workspace protocols
   - \`HEARTBEAT.md\` - Periodic check tasks
   - \`config.json\` - Agent configuration

2. **Install recommended skills:**
   ${skillData.recommended.map(s => `- ${s}`).join('\n   ')}

3. **Deploy to OpenClaw:**
   - Copy this workspace to your OpenClaw instance
   - Configure the agent with the recommended model
   - Enable the recommended skills

## Next Steps

- Review and approve the skill recommendations
- Customize the templates to match your organization
- Test the agent in a controlled environment
- Deploy to production when ready

---

*Generated by DISC Agent Blueprint System v0.1.0*
`;
  
  fs.writeFileSync(path.join(agentDir, 'README.md'), readmeContent);
  log(`  ✓ README.md`, 'green');
  
  // Summary
  log(`\n${'='.repeat(60)}`, 'cyan');
  log(`Agent Workspace Created Successfully!`, 'green');
  log(`${'='.repeat(60)}`, 'cyan');
  log(`\nLocation: ${agentDir}`, 'cyan');
  log(`\nNext Steps:`, 'yellow');
  log(`  1. Review the generated files in ${agentDir}`, 'yellow');
  log(`  2. Install the recommended skills (manual approval required)`, 'yellow');
  log(`  3. Customize templates as needed`, 'yellow');
  log(`  4. Deploy to your OpenClaw instance`, 'yellow');
  log(`\n${'='.repeat(60)}\n`, 'cyan');
  
  return {
    success: true,
    agentDir,
    skillData,
    roleDef
  };
}

/**
 * Parse command line arguments
 */
function parseArgs(args) {
  const options = {
    role: null,
    name: null,
    output: './generated-agents',
    help: false
  };
  
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    
    if (arg === '--help' || arg === '-h') {
      options.help = true;
    } else if (arg.startsWith('--role=')) {
      options.role = arg.split('=')[1];
    } else if (arg.startsWith('--name=')) {
      options.name = arg.split('=')[1];
    } else if (arg.startsWith('--output=')) {
      options.output = arg.split('=')[1];
    }
  }
  
  return options;
}

/**
 * Show help
 */
function showHelp() {
  console.log(`
${colors.cyan}DISC Agent Blueprint Generator${colors.reset}

${colors.magenta}Usage:${colors.reset}
  node create-agent.js --role=<role> --name=<agent-name> [--output=<directory>]

${colors.magenta}Options:${colors.reset}
  --role=<role>     Role type (hr-specialist, developer, marketing, sales, customer-support, finance-ops)
  --name=<name>     Agent name (e.g., "Sarah", "Alex")
  --output=<dir>    Output directory (default: ./generated-agents)
  --help, -h        Show this help message

${colors.magenta}Examples:${colors.reset}
  node create-agent.js --role=hr-specialist --name="Sarah"
  node create-agent.js --role=developer --name="Alex" --output="./my-agents"

${colors.magenta}Available Roles:${colors.reset}
  hr-specialist     - HR Specialist (S+C profile)
  developer         - Developer (C+D profile)
  marketing         - Marketing Specialist (I+S profile)
  sales             - Sales Representative (D+I profile)
  customer-support  - Customer Support (S+I profile)
  finance-ops       - Finance & Operations (C+D profile)

${colors.yellow}Note: Skills are recommended for manual approval, not auto-installed.${colors.reset}
`);
}

// Main execution
const args = process.argv.slice(2);
const options = parseArgs(args);

if (options.help || !options.role || !options.name) {
  showHelp();
  process.exit(options.help ? 0 : 1);
}

// Create the agent
const result = createAgent(options.role, options.name, options.output);

process.exit(result.success ? 0 : 1);
